-- Starting item list (requirement F31, design D6): the previous catalog, 102 items in 11
-- categories, with the last ODEPA market prices it had (25 Sept 2026).

INSERT INTO categories (id, name_es, name_en, icon, sort) VALUES
    (1, 'Verduras', 'Vegetables', '🥕', 10),
    (2, 'Hierbas y hojas', 'Herbs & Greens', '🌿', 20),
    (3, 'Frutas', 'Fruits', '🍋', 30),
    (4, 'Lácteos y huevos', 'Dairy & Eggs', '🥛', 40),
    (5, 'Carnes y aves', 'Meat & Poultry', '🍗', 50),
    (6, 'Pescados y mariscos', 'Seafood', '🐟', 60),
    (7, 'Abarrotes', 'Grocery & Dry', '🌾', 70),
    (8, 'Especias', 'Spices', '🌶️', 80),
    (9, 'Aceites y salsas', 'Oils & Sauces', '🫙', 90),
    (10, 'Bebidas', 'Beverages', '🥤', 100),
    (11, 'Limpieza y envases', 'Cleaning & Packing', '🧽', 110);

INSERT INTO items (category_id, name_es, name_en, unit, price, price_source, market_keywords, market_price, market_prev, market_date, market_quote, sort, updated_at) VALUES
    (1, 'Cebolla morada', 'Onion (red)', 'kg', 900, 'market', 'cebolla morada, cebolla', 950, NULL, '2026-09-25', '$19.000 $/caja 20 kilos (vega central mapocho de santiago)', 10, NOW()),
    (1, 'Cebolla', 'Onion (white)', 'kg', 800, 'market', 'cebolla', 950, NULL, '2026-09-25', '$19.000 $/caja 20 kilos (vega central mapocho de santiago)', 20, NOW()),
    (1, 'Tomate', 'Tomato', 'kg', 1300, 'market', 'tomate', 1118, NULL, '2026-09-25', '$20.440 $/bandeja 18 kilos (mercado mayorista lo valledor de santiago)', 30, NOW()),
    (1, 'Papa', 'Potato', 'kg', 700, 'market', 'papa', 930, NULL, '2026-09-25', '$23.000 $/saco 25 kilos (vega central mapocho de santiago)', 40, NOW()),
    (1, 'Ajo', 'Garlic', 'kg', 4500, 'market', 'ajo', 1600, NULL, '2026-09-25', '$16.000 $/caja 10 kilos (mercado mayorista lo valledor de santiago)', 50, NOW()),
    (1, 'Jengibre', 'Ginger', 'kg', 5500, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (1, 'Ají verde', 'Green chili', 'kg', 3500, 'market', 'aji verde, aji', 5680, NULL, '2026-09-25', '$142.000 $/caja 25 kilos (vega central mapocho de santiago)', 70, NOW()),
    (1, 'Pimentón verde', 'Capsicum (green)', 'kg', 1800, 'market', 'pimenton verde, pimenton', NULL, NULL, NULL, '', 80, NOW()),
    (1, 'Pimentón rojo', 'Capsicum (red)', 'kg', 2500, 'market', 'pimenton rojo, pimenton', NULL, NULL, NULL, '', 90, NOW()),
    (1, 'Zanahoria', 'Carrot', 'kg', 700, 'market', 'zanahoria', 906, NULL, '2026-09-25', '$18.250 $/saco 20 kilos (vega central mapocho de santiago)', 100, NOW()),
    (1, 'Coliflor', 'Cauliflower', 'unit', 1500, 'market', 'coliflor', 623, NULL, '2026-09-25', '$645 $/unidad (mercado mayorista lo valledor de santiago)', 110, NOW()),
    (1, 'Repollo', 'Cabbage', 'unit', 1200, 'market', 'repollo', 1500, NULL, '2026-09-25', '$1.500 $/unidad (mercado mayorista lo valledor de santiago)', 120, NOW()),
    (1, 'Berenjena', 'Eggplant', 'kg', 1600, 'market', 'berenjena', NULL, NULL, NULL, '', 130, NOW()),
    (1, 'Okra', 'Okra (bhindi)', 'kg', 6000, 'manual', '', NULL, NULL, NULL, '', 140, NOW()),
    (1, 'Zapallo italiano', 'Zucchini', 'kg', 1200, 'market', 'zapallo italiano', NULL, NULL, NULL, '', 150, NOW()),
    (1, 'Zapallo camote', 'Pumpkin', 'kg', 900, 'market', 'zapallo camote, zapallo', 1080, NULL, '2026-09-25', '$1.080 $/kilo (volumen en unidades) (mercado mayorista lo valledor de santiago)', 160, NOW()),
    (1, 'Pepino', 'Cucumber', 'unit', 500, 'market', 'pepino ensalada, pepino', 333, NULL, '2026-09-25', '$20.000 $/caja 60 unidades (vega central mapocho de santiago)', 170, NOW()),
    (1, 'Arveja verde', 'Green peas', 'kg', 2500, 'market', 'arveja verde, arveja', 880, NULL, '2026-09-25', '$22.000 $/malla 25 kilos (vega central mapocho de santiago)', 180, NOW()),
    (1, 'Poroto verde', 'Green beans', 'kg', 2000, 'market', 'poroto verde', 2120, NULL, '2026-09-25', '$53.000 $/malla 25 kilos (vega central mapocho de santiago)', 190, NOW()),
    (1, 'Champiñón', 'Mushroom', 'kg', 4500, 'manual', '', NULL, NULL, NULL, '', 200, NOW()),
    (1, 'Betarraga', 'Beetroot', 'kg', 900, 'market', 'betarraga', NULL, NULL, NULL, '', 210, NOW()),
    (1, 'Choclo', 'Sweet corn', 'unit', 400, 'market', 'choclo', 933, NULL, '2026-09-25', '$56.000 $/malla 60 unidades (vega central mapocho de santiago)', 220, NOW()),
    (2, 'Cilantro', 'Coriander', 'bunch', 500, 'market', 'cilantro', 744, NULL, '2026-09-25', '$15.000 $/docena de atados (mercado mayorista lo valledor de santiago)', 10, NOW()),
    (2, 'Menta', 'Mint', 'bunch', 600, 'market', 'menta', NULL, NULL, NULL, '', 20, NOW()),
    (2, 'Espinaca', 'Spinach', 'kg', 2500, 'market', 'espinaca', 977, NULL, '2026-09-25', '$8.538 $/cuna 10 kilos (mercado mayorista lo valledor de santiago)', 30, NOW()),
    (2, 'Lechuga', 'Lettuce', 'unit', 700, 'market', 'lechuga', 567, NULL, '2026-09-25', '$8.500 $/caja 15 unidades (vega central mapocho de santiago)', 40, NOW()),
    (2, 'Cebollín', 'Spring onion', 'bunch', 500, 'market', 'cebollin', 667, NULL, '2026-09-25', '$8.000 $/docena de paquetes (vega modelo de temuco)', 50, NOW()),
    (2, 'Hojas de curry', 'Curry leaves', 'pack', 2000, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (2, 'Fenogreco', 'Fenugreek (methi)', 'pack', 2500, 'manual', '', NULL, NULL, NULL, '', 70, NOW()),
    (3, 'Limón', 'Lemon', 'kg', 1500, 'market', 'limon', 258, NULL, '2026-09-25', '$4.639 $/malla 18 kilos (vega central mapocho de santiago)', 10, NOW()),
    (3, 'Lima', 'Lime', 'kg', 3000, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (3, 'Plátano', 'Banana', 'kg', 1200, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (3, 'Mango', 'Mango', 'unit', 1500, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (3, 'Piña', 'Pineapple', 'unit', 2500, 'manual', '', NULL, NULL, NULL, '', 50, NOW()),
    (3, 'Manzana', 'Apple', 'kg', 1200, 'market', 'manzana', 750, NULL, '2026-09-25', '$300.000 $/bins (400 kilos) (mercado mayorista lo valledor de santiago)', 60, NOW()),
    (3, 'Naranja', 'Orange', 'kg', 1100, 'market', 'naranja', 329, NULL, '2026-09-25', '$130.000 $/bins (400 kilos) (mercado mayorista lo valledor de santiago)', 70, NOW()),
    (3, 'Palta', 'Avocado', 'kg', 3500, 'market', 'palta hass, palta', 3000, NULL, '2026-09-25', '$30.000 $/bandeja 10 kilos (vega central mapocho de santiago)', 80, NOW()),
    (4, 'Leche entera', 'Milk (whole)', 'l', 1100, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (4, 'Crema', 'Cream', 'l', 5500, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (4, 'Yogur natural', 'Plain yogurt', 'kg', 3500, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (4, 'Mantequilla', 'Butter', 'kg', 11000, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (4, 'Ghee', 'Ghee', 'kg', 18000, 'manual', '', NULL, NULL, NULL, '', 50, NOW()),
    (4, 'Paneer', 'Paneer', 'kg', 12000, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (4, 'Queso mozzarella', 'Mozzarella', 'kg', 9000, 'manual', '', NULL, NULL, NULL, '', 70, NOW()),
    (4, 'Huevos', 'Eggs (tray of 30)', 'tray', 7500, 'manual', '', NULL, NULL, NULL, '', 80, NOW()),
    (5, 'Pechuga deshuesada', 'Chicken boneless', 'kg', 6500, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (5, 'Trutro de pollo', 'Chicken leg / thigh', 'kg', 3800, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (5, 'Pollo entero', 'Chicken whole', 'kg', 3200, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (5, 'Cordero', 'Lamb', 'kg', 12000, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (5, 'Cabrito', 'Goat / mutton', 'kg', 11000, 'manual', '', NULL, NULL, NULL, '', 50, NOW()),
    (5, 'Carne de vacuno', 'Beef', 'kg', 10000, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (5, 'Pollo molido', 'Chicken mince', 'kg', 5500, 'manual', '', NULL, NULL, NULL, '', 70, NOW()),
    (6, 'Camarón', 'Prawns', 'kg', 14000, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (6, 'Salmón', 'Salmon', 'kg', 13000, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (6, 'Reineta', 'White fish (reineta)', 'kg', 9000, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (7, 'Arroz basmati', 'Basmati rice', 'kg', 3500, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (7, 'Arroz', 'Rice (regular)', 'kg', 1400, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (7, 'Harina integral', 'Atta (wheat flour)', 'kg', 1500, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (7, 'Harina', 'Maida (flour)', 'kg', 1000, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (7, 'Harina de garbanzo', 'Besan (gram flour)', 'kg', 4000, 'manual', '', NULL, NULL, NULL, '', 50, NOW()),
    (7, 'Toor dal', 'Toor dal', 'kg', 4500, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (7, 'Lenteja roja', 'Masoor dal (red lentil)', 'kg', 3000, 'manual', '', NULL, NULL, NULL, '', 70, NOW()),
    (7, 'Chana dal', 'Chana dal', 'kg', 4000, 'manual', '', NULL, NULL, NULL, '', 80, NOW()),
    (7, 'Garbanzos', 'Chickpeas', 'kg', 2800, 'manual', '', NULL, NULL, NULL, '', 90, NOW()),
    (7, 'Porotos rojos', 'Kidney beans (rajma)', 'kg', 3200, 'manual', '', NULL, NULL, NULL, '', 100, NOW()),
    (7, 'Azúcar', 'Sugar', 'kg', 1200, 'manual', '', NULL, NULL, NULL, '', 110, NOW()),
    (7, 'Sal', 'Salt', 'kg', 500, 'manual', '', NULL, NULL, NULL, '', 120, NOW()),
    (7, 'Castañas de cajú', 'Cashew', 'kg', 16000, 'manual', '', NULL, NULL, NULL, '', 130, NOW()),
    (7, 'Almendras', 'Almond', 'kg', 12000, 'manual', '', NULL, NULL, NULL, '', 140, NOW()),
    (7, 'Pasta de tomate', 'Tomato purée', 'kg', 2500, 'manual', '', NULL, NULL, NULL, '', 150, NOW()),
    (7, 'Leche de coco', 'Coconut milk', 'can', 1800, 'manual', '', NULL, NULL, NULL, '', 160, NOW()),
    (8, 'Cúrcuma', 'Turmeric powder', 'kg', 9000, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (8, 'Ají en polvo', 'Red chili powder', 'kg', 10000, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (8, 'Ají Kashmiri', 'Kashmiri chili', 'kg', 14000, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (8, 'Cilantro molido', 'Coriander powder', 'kg', 8000, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (8, 'Comino entero', 'Cumin seeds', 'kg', 12000, 'manual', '', NULL, NULL, NULL, '', 50, NOW()),
    (8, 'Garam masala', 'Garam masala', 'kg', 16000, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (8, 'Cardamomo', 'Green cardamom', 'kg', 60000, 'manual', '', NULL, NULL, NULL, '', 70, NOW()),
    (8, 'Clavo de olor', 'Cloves', 'kg', 30000, 'manual', '', NULL, NULL, NULL, '', 80, NOW()),
    (8, 'Canela', 'Cinnamon', 'kg', 15000, 'manual', '', NULL, NULL, NULL, '', 90, NOW()),
    (8, 'Laurel', 'Bay leaf', 'kg', 10000, 'manual', '', NULL, NULL, NULL, '', 100, NOW()),
    (8, 'Semillas de mostaza', 'Mustard seeds', 'kg', 7000, 'manual', '', NULL, NULL, NULL, '', 110, NOW()),
    (8, 'Fenogreco seco', 'Kasuri methi', 'kg', 15000, 'manual', '', NULL, NULL, NULL, '', 120, NOW()),
    (8, 'Azafrán', 'Saffron', 'g', 5000, 'manual', '', NULL, NULL, NULL, '', 130, NOW()),
    (9, 'Aceite vegetal', 'Vegetable oil', 'l', 2200, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (9, 'Aceite de mostaza', 'Mustard oil', 'l', 7000, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (9, 'Vinagre', 'Vinegar', 'l', 1200, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (9, 'Salsa de soya', 'Soy sauce', 'l', 3500, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (9, 'Kétchup', 'Ketchup', 'kg', 3000, 'manual', '', NULL, NULL, NULL, '', 50, NOW()),
    (9, 'Mayonesa', 'Mayonnaise', 'kg', 4000, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (10, 'Agua mineral', 'Mineral water 500 ml (pack of 12)', 'pack', 6000, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (10, 'Bebidas lata', 'Soft drinks 350 ml (pack of 6)', 'pack', 5000, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (10, 'Té', 'Tea (loose)', 'kg', 12000, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (10, 'Café', 'Coffee', 'kg', 18000, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (11, 'Lavaloza', 'Dishwash liquid', 'l', 2500, 'manual', '', NULL, NULL, NULL, '', 10, NOW()),
    (11, 'Cloro', 'Bleach', 'l', 1200, 'manual', '', NULL, NULL, NULL, '', 20, NOW()),
    (11, 'Bolsas de basura', 'Garbage bags', 'pack', 3000, 'manual', '', NULL, NULL, NULL, '', 30, NOW()),
    (11, 'Papel aluminio', 'Aluminium foil', 'roll', 4500, 'manual', '', NULL, NULL, NULL, '', 40, NOW()),
    (11, 'Film plástico', 'Cling film', 'roll', 4000, 'manual', '', NULL, NULL, NULL, '', 50, NOW()),
    (11, 'Envases', 'Takeaway containers (pack of 50)', 'pack', 9000, 'manual', '', NULL, NULL, NULL, '', 60, NOW()),
    (11, 'Servilletas', 'Napkins', 'pack', 2500, 'manual', '', NULL, NULL, NULL, '', 70, NOW()),
    (11, 'Guantes', 'Gloves', 'box', 5000, 'manual', '', NULL, NULL, NULL, '', 80, NOW());

UPDATE settings SET value = '2026-09-25' WHERE name = 'market_date';
